name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop]

jobs:
  deployFunctions:
    name: Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Depedencies
        run: npm install
        working-directory: functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy use dev
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_CI}}